version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
    - ../..:/workspaces:cached

    command: sleep infinity

  wiremock:
    image: wiremock/wiremock
    ports:
    - 8080:8080
    volumes:
    - ./infra/wiremock:/home/wiremock
